---
title: "Untitled"
output: html_document
date: "2023-08-27"
---

Load packages

```{R}
library(ggplot2)

library(readr)

library(dplyr)

library(EnvStats)

library(outliers)

```

```{R}

assogrids <- read.csv('~/Desktop/association/grid_level_association_50km_sig_180s_20240606_reserved_nocover.csv')


head(assogrids, 10L)


names(assogrids)


```

```{r}

nrow(assogrids[assogrids$assosimple>=0 & assogrids$associationpvalue<0.05,])/nrow(assogrids)

nrow(assogrids[assogrids$assosimple<0 & assogrids$associationpvalue<0.05,])/nrow(assogrids)

```



```{R}


test <- rosnerTest(assogrids[,'assosimple'], k = 100)$all.stats

test <- test[test$Outlier == 'TRUE',]

assogrids <- assogrids[-test$Obs.Num,]


"test <- rosnerTest(assogrids[,'assoneg'], k = 100)$all.stats

test <- test[test$Outlier == 'TRUE',]

assogrids <- assogrids[-test$Obs.Num,]"




```


```{r}

```



```{R}

assogrids <- assogrids %>%
  mutate(plotcount = case_when(nplot>=180 ~ 180,
                               nplot<180 ~ nplot))

assogrids %>%
  ggplot(., aes(x = plotcount, y = assosimple))+
  geom_point(alpha = 0.6)+
  geom_quantile(quantiles = c(0.1,0.9), method = 'rqss')+
  geom_smooth(method = 'gam', se = FALSE)+
  scale_x_continuous(trans = 'log10')+
  theme_classic()+
  labs(x='Number of plots', y = 'Species association')+
  theme(axis.title = element_text(color = '#000000', size = 20), axis.text = element_text(color = '#000000', size = 20))
  

assogrids %>%
  ggplot(., aes(x = nplot, y = regionalrichness))+
  geom_point()+
  geom_smooth(method = 'gam')+
  scale_x_continuous(trans = 'log10')

assogrids %>%
  ggplot(., aes(x = nplot, y = assosimple))+
  geom_point()+
  geom_smooth(method = 'gam')+
  scale_x_continuous(trans = 'log10')


assogrids %>%
  ggplot(., aes(x = nplot, y = CHELSA_Annual_Mean_Temperature_mean))+
  geom_point()+
  geom_smooth(method = 'gam')

assogrids %>%
  ggplot(., aes(x = nplot, y = CHELSA_Annual_Precipitation_mean))+
  geom_point()+
  geom_smooth(method = 'gam')+
  scale_x_continuous(trans = 'log10')

assogrids %>%
  ggplot(., aes(x = nplot, y = CHELSA_Annual_Mean_Temperature_std))+
  geom_point()+
  geom_smooth(method = 'gam')+
  scale_x_continuous(trans = 'log10')

```

```{R}

summary(lm(assosimple~plotcount, data = assogrids))



```

```{R}

nrow(assogrids[assogrids$associationpvalue <0.05 & assogrids$assosimple>=0,])/nrow(assogrids)

nrow(assogrids[assogrids$associationpvalue <0.05 & assogrids$assosimple<0,])/nrow(assogrids)

nrow(assogrids[assogrids$assosimple<0,])/nrow(assogrids)

nrow(assogrids[assogrids$assosimple>=0,])/nrow(assogrids)

```

```{R}

assogrids %>%
  ggplot(., aes(x = lat, y = associatoinsimplespear))+
  geom_point(alpha = 0.05)+
  geom_smooth(method = 'loess', span = 0.8, color = '#000000', size = 2)+
  labs(x = 'Latitude', y = 'Species association')+
  theme_classic()+
  theme(axis.title = element_text(color = '#000000', size = 20), axis.text = element_text(color = '#000000', size = 20))
  #coord_flip(ylim = c(-0.5,0.1))


assogrids %>%
  ggplot(., aes(x = lon, y = associatoinsimplespear))+
  geom_point(alpha = 0.05)+
  geom_smooth(method = 'loess', span = 0.8, color = '#000000', size = 2)+
  labs(x = 'Longitude', y = 'Species association')+
  theme_classic()+
  #coord_cartesian(ylim = c(-0.5,0.1))+
  theme(axis.title = element_text(color = '#000000', size = 20), axis.text = element_text(color = '#000000', size = 20))


```

```{R}


summary(assogrids$assosimple)


assogrids %>%
  ggplot(., aes(x = assosimple))+
  geom_histogram()

#summary(assogrids$asson)


```

```{R}

assogrids %>%
  ggplot(., aes(x = CHELSA_Annual_Mean_Temperature_std))+
  geom_histogram()


assogrids %>%
  ggplot(., aes(x = CHELSA_Annual_Precipitation_std))+
  geom_histogram()



```

```{r}

summary(assogrids$CHELSA_Annual_Mean_Temperature_std)

summary(assogrids$CHELSA_Annual_Precipitation_std)



```

```{R}

assogrids %>%
  ggplot(., aes(x = CHELSA_Annual_Mean_Temperature_std, y = assosimple))+
  geom_point()+
  geom_smooth()+
  scale_x_continuous(trans = 'log10')



assogrids %>%
  ggplot(., aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assosimple))+
  geom_point()+
  geom_smooth()


```

```{R}


assogrids %>%
  ggplot(., aes(x = EarthEnvTopoMed_Elevation_mean, y = assosimple))+
  geom_point(alpha = 0.2)+
  geom_smooth()+
  scale_x_continuous(trans = 'log10')

summary(assogrids$EarthEnvTopoMed_Elevation_mean)
```

```{R}

paletteForUse <- c('#FF0000',"#FDE725", "#AADC32", "#5DC863", "#27AD81", "#21908C", "#2C728E", "#3B528B", "#472D7B", "#440154")
colors <-  colorRampPalette(paletteForUse)(256)


assogrids$dens <- col2rgb(densCols(assogrids$regionalrichness, assogrids$asso))[1,]+1L
assogrids$colors = colors[assogrids$dens]
range(assogrids$dens)
quantile(assogrids$dens,0.9)
assogrids[assogrids$dens >133, 'colors'] = '#BEBEBE' # Here you have to check the 90% quantile of the column 'dens'



```

```{R}

assogrids %>%
  ggplot(., aes(x = asso, y = regionalrichness))+
  geom_point(alpha = 0.5, color = assogrids$colors)+
  geom_smooth(method = 'loess', span = 100, degree = 1)
  #scale_y_continuous(trans = 'log10')


```

```{R}

paletteForUse <- c('#FF0000',"#FDE725", "#AADC32", "#5DC863", "#27AD81", "#21908C", "#2C728E", "#3B528B", "#472D7B", "#440154")
colors <-  colorRampPalette(paletteForUse)(256)


assogrids$dens <- col2rgb(densCols(assogrids$npp_mean, assogrids$asso))[1,]+1L
assogrids$colors = colors[assogrids$dens]
range(assogrids$dens)
quantile(assogrids$dens,0.9)
assogrids[assogrids$dens >142, 'colors'] = '#BEBEBE' # Here you have to check the 90% quantile of the column 'dens'



```

```{R}
assogrids %>%
  ggplot(., aes(x = asso, y = npp_mean))+
  geom_point(alpha = 0.5, color = assogrids$colors)+
  geom_smooth(method = 'gam')
  #scale_y_continuous(trans = 'log10')





```

```{R}

paletteForUse <- c('#FF0000',"#FDE725", "#AADC32", "#5DC863", "#27AD81", "#21908C", "#2C728E", "#3B528B", "#472D7B", "#440154")
colors <-  colorRampPalette(paletteForUse)(256)


assogrids$dens <- col2rgb(densCols(assogrids$regionalrichness, assogrids$assoneg))[1,]+1L
assogrids$colors = colors[assogrids$dens]
range(assogrids$dens)
quantile(assogrids$dens,0.9)
assogrids[assogrids$dens >137, 'colors'] = '#BEBEBE' # Here you have to check the 90% quantile of the column 'dens'



```

```{R}

assogrids %>%
  ggplot(., aes(x = assoneg, y = regionalrichness))+
  geom_point(alpha = 0.5, color = assogrids$colors)+
  geom_smooth(method = 'loess', span = 1)
  #scale_y_continuous(trans = 'log10')

```

```{R}

paletteForUse <- c('#FF0000',"#FDE725", "#AADC32", "#5DC863", "#27AD81", "#21908C", "#2C728E", "#3B528B", "#472D7B", "#440154")
colors <-  colorRampPalette(paletteForUse)(256)


assogrids$dens <- col2rgb(densCols(assogrids$npp_mean, assogrids$assoneg))[1,]+1L
assogrids$colors = colors[assogrids$dens]
range(assogrids$dens)
quantile(assogrids$dens,0.9)
assogrids[assogrids$dens >147, 'colors'] = '#BEBEBE' # Here you have to check the 90% quantile of the column 'dens'



```

```{R}
assogrids %>%
  ggplot(., aes(x = assoneg, y = npp_mean))+
  geom_point(alpha = 0.5, color = assogrids$colors)+
  geom_smooth(method = 'loess', span = 1)
  #scale_y_continuous(trans = 'log10')

```

```{R}

  summary(lm(regionalrichness ~ assosimple,data = assogrids))

#summary(lm(log10(regionalrichness) ~ assosimple+ regionaldensity,data = assogrids))


```

```{R}

assogrids %>%
  ggplot(., aes(x = regionalrichness, y = assosimple))+
  geom_point(alpha = 0.2)+
  geom_smooth()+
  labs(x = 'Grid level species richness', y = 'Species association')+
  theme_classic()+
  theme(axis.text = element_text(color = '#000000', size = 20), axis.title = element_text(color = '#000000', size = 20))
  #scale_x_continuous(trans = 'log10')


```

```{R}

assogrids %>%
  ggplot(., aes(x = nplot))+
  geom_histogram(bins = 100)+
  scale_x_continuous(trans = 'log10')



```

```{R}

fit1 <- lm(log10(regionalrichness) ~ regionaldensity, data = assogrids)

fit2 <- lm(asso~regionaldensity, data = assogrids)

fit3 <- lm(assoneg ~ regionaldensity, data = assogrids)

fit4 <- lm(npp_mean ~ regionaldensity, data=assogrids)

summary(lm(fit1$residuals ~ fit2$residuals + fit3$residuals))


summary(lm(fit1$residuals ~ fit2$residuals ))

summary(lm(fit1$residuals ~ fit3$residuals ))


summary(lm(fit4$residuals ~ fit2$residuals + fit3$residuals))


```

```{R}

assogrids$richnessresidual <- fit1$residuals

assogrids$assoresidual <- fit2$residuals

assogrids$assonegresidual <- fit3$residuals

assogrids$nppresidual <- fit4$residuals

```

```{R}
library(ggparty)
library(partykit)
```

```{R}

assotree <- lmtree(assosimple~CHELSA_Annual_Mean_Temperature_mean | CHELSA_Precipitation_of_Driest_Quarter_mean, maxdepth = 3, minsplit = 456, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = CHELSA_Annual_Mean_Temperature_mean,
                                               y = assosimple),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assosimple), alpha = 0.1),
                               theme_classic()
 
                 )
  )

```

```{R}

summary(assogrids$CHELSA_Precipitation_of_Driest_Quarter_mean)
summary(assogrids$CHELSA_Annual_Mean_Temperature_mean)

summary(assogrids$CHELSA_Annual_Precipitation_mean)

```

```{R}

library(lme4)

sub1 <- assogrids %>%
  filter(CHELSA_Precipitation_of_Driest_Quarter_mean<200) %>%
  mutate(precate = '1~200')

sub5 <- assogrids %>%
  filter(CHELSA_Precipitation_of_Driest_Quarter_mean>=250 & CHELSA_Precipitation_of_Driest_Quarter_mean < 300) %>%
  mutate(precate = "250~414")



sub2 <- assogrids %>%
  filter(CHELSA_Precipitation_of_Driest_Quarter_mean>=140 & CHELSA_Precipitation_of_Driest_Quarter_mean < 200) %>%
  mutate(precate = "1~200")

sub3 <- assogrids %>%
  filter(CHELSA_Precipitation_of_Driest_Quarter_mean >= 200 & CHELSA_Precipitation_of_Driest_Quarter_mean < 250) %>%
  mutate(precate = "200~250")

sub4 <- assogrids %>%
  filter(CHELSA_Precipitation_of_Driest_Quarter_mean >= 300) %>%
  mutate(precate = '250~414')


newdf <- rbind(sub1, sub3, sub4, sub5)


models <- lmList(scale(assosimple)~scale(CHELSA_Annual_Mean_Temperature_mean) | precate, data = newdf)

ss <- summary(models)

items <- unique(newdf$precate)

coefs <- c(ss$coefficients[1,1,2], ss$coefficients[2,1,2], ss$coefficients[3,1,2])
coefs <- as.numeric(coefs)

stdrs <- c(ss$coefficients[1,2,2], ss$coefficients[2,2,2], ss$coefficients[3,2,2])

modeldf <- cbind(items, coefs, stdrs)

modeldf <- as.data.frame(modeldf)
modeldf$coefs <- coefs
modeldf$stdrs <- stdrs
ggplot(modeldf, aes(x = items, y = coefs))+
  geom_point(size = 6.18)+
  geom_errorbar(aes(ymin = coefs - 2*stdrs, ymax = coefs + 2*stdrs), width = 0, size = 1)+
  geom_hline(yintercept = 0, linetype = 'dashed')


```

```{R}

set.seed(100)
assotree <- ctree(assosimple~CHELSA_Annual_Mean_Temperature_mean + CHELSA_Annual_Precipitation_mean, data = assogrids, control = ctree_control(maxdepth = 3, mtry = 2, minprob = 0.2))

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_boxplot(aes(x =" ", y = assosimple), outlier.shape = NA),
                               theme_classic(),
                               theme(axis.title = element_text(size = 20, color = '#000000'), axis.text = element_text(size = 20, color = '#000000'), plot.margin = margin(0,1,0,1,unit = 'cm'))
 
                 ),
                 shared_axis_labels = T, 
                 shared_legend = T
  )



```

```{R}

hotdf <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 140)

middf <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >=80 & CHELSA_Annual_Mean_Temperature_mean <140)

colddf <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean<80)

summary(hotdf$CHELSA_Annual_Precipitation_mean)

summary(colddf$CHELSA_Annual_Precipitation_mean)

hot1 <- hotdf %>%
  filter(CHELSA_Annual_Precipitation_mean<800) %>%
  mutate(temp = 'hot', 
         pre = '<800')

hot2 <- hotdf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 800 & CHELSA_Annual_Precipitation_mean < 1200) %>%
  mutate(temp = 'hot',
         pre = '800~1200')

hot3 <- hotdf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1200 & CHELSA_Annual_Precipitation_mean < 1600) %>%
  mutate(temp = 'hot',
         pre = '1200~1600')

hot4 <- hotdf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1600) %>%
  mutate(temp = 'hot',
         pre = '>=1600')


mid1 <- middf %>%
  filter(CHELSA_Annual_Precipitation_mean<800) %>%
  mutate(temp = 'mid', 
         pre = '<800')

mid2 <- middf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 800 & CHELSA_Annual_Precipitation_mean < 1200) %>%
  mutate(temp = 'mid',
         pre = '800~1200')

mid3 <- middf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1200 & CHELSA_Annual_Precipitation_mean < 1600) %>%
  mutate(temp = 'mid',
         pre = '1200~1600')

mid4 <- middf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1600) %>%
  mutate(temp = 'mid',
         pre = '>=1600')




cold1 <- colddf %>%
  filter(CHELSA_Annual_Precipitation_mean<800) %>%
  mutate(temp = 'cold',
         pre = '<800')

cold2 <- colddf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 800  & CHELSA_Annual_Precipitation_mean < 1200) %>%
  mutate(temp = 'cold',
         pre = '800~1200')

cold3 <- colddf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1200 & CHELSA_Annual_Precipitation_mean < 1600) %>%
  mutate(temp = 'cold',
         pre = '1200~1600')

cold4 <- colddf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1600) %>%
  mutate(temp = 'cold',
         pre = '>=1600')



newdf <- rbind(hot1, hot2, hot3, hot4,mid1,mid2,mid3,mid4, cold1, cold2, cold3, cold4)
pres <- unique(newdf$pre)

newdf$pre <- factor(newdf$pre, levels = pres)

p3<-newdf %>%
  ggplot(., aes(x = pre, y = assosimple, color = temp))+
  stat_summary(fun.data = 'mean_cl_boot', size = 1.5)+
  stat_summary(fun = mean, geom = 'line', size = 1, aes(group = temp))+
  labs(x = 'Annual precipitation', y = 'Grid-level\n mean association')+
  theme_classic()+
  scale_color_manual(values = c('#2166AC','#B2182B', '#999999'))+
  geom_abline(slope = 0, intercept = 0,linetype = 'dashed')+
  theme(axis.title = element_text(size = 20, color = '#000000'), axis.text = element_text(size = 20,color = '#000000'), legend.position = 'none', plot.margin = margin(1,1,1,1,unit = 'cm'))
  
newdf %>%
  ggplot(., aes(x = pre, y = assosimple, color = temp))+
  stat_summary(fun.data = 'mean_cl_boot', size = 1.5)+
  stat_summary(fun = mean, geom = 'line', size = 1, aes(group = temp))+
  labs(x = 'Annual precipitation', y = 'Grid-level\n mean association')+
  theme_classic()+
  scale_color_manual(values = c('#2166AC', '#B2182B', '#999999'))+
  geom_abline(slope = 0, intercept = 0,linetype = 'dashed')+
  theme(axis.title = element_text(size = 20, color = '#000000'), axis.text = element_text(size = 20,color = '#000000'), plot.margin = margin(1,1,1,1,unit = 'cm'))

```

```{R}

hotdf <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 140)

middf <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >=80 & CHELSA_Annual_Mean_Temperature_mean <140)

colddf <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean<80)

summary(hotdf$CHELSA_Annual_Precipitation_mean)

summary(colddf$CHELSA_Annual_Precipitation_mean)

hot1 <- hotdf %>%
  filter(CHELSA_Annual_Precipitation_mean<800) %>%
  mutate(temp = '>=14', 
         pre = '<800',
         meanasso = mean(assosimple))

hot2 <- hotdf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 800 & CHELSA_Annual_Precipitation_mean < 1200) %>%
  mutate(temp = '>=14',
         pre = '800~1200',
         meanasso = mean(assosimple))

hot3 <- hotdf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1200 & CHELSA_Annual_Precipitation_mean < 1600) %>%
  mutate(temp = '>=14',
         pre = '1200~1600',
         meanasso = mean(assosimple))

hot4 <- hotdf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1600) %>%
  mutate(temp = '>=14',
         pre = '>=1600',
         meanasso = mean(assosimple))


mid1 <- middf %>%
  filter(CHELSA_Annual_Precipitation_mean<800) %>%
  mutate(temp = '8~14', 
         pre = '<800',
         meanasso = mean(assosimple))

mid2 <- middf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 800 & CHELSA_Annual_Precipitation_mean < 1200) %>%
  mutate(temp = '8~14',
         pre = '800~1200',
         meanasso = mean(assosimple))

mid3 <- middf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1200 & CHELSA_Annual_Precipitation_mean < 1600) %>%
  mutate(temp = '8~14',
         pre = '1200~1600',
         meanasso = mean(assosimple))

mid4 <- middf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1600) %>%
  mutate(temp = '8~14',
         pre = '>=1600',
         meanasso = mean(assosimple))




cold1 <- colddf %>%
  filter(CHELSA_Annual_Precipitation_mean<800) %>%
  mutate(temp = '<8',
         pre = '<800',
         meanasso = mean(assosimple))

cold2 <- colddf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 800  & CHELSA_Annual_Precipitation_mean < 1200) %>%
  mutate(temp = '<8',
         pre = '800~1200',
         meanasso = mean(assosimple))

cold3 <- colddf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1200 & CHELSA_Annual_Precipitation_mean < 1600) %>%
  mutate(temp = '<8',
         pre = '1200~1600',
         meanasso = mean(assosimple))

cold4 <- colddf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1600) %>%
  mutate(temp = '<8',
         pre = '>=1600',
         meanasso = mean(assosimple))


newdf <- rbind(hot1, hot2, hot3, hot4,mid1,mid2,mid3,mid4, cold1, cold2, cold3, cold4)

newdf$temp <- factor(newdf$temp, levels = c('<8', '8~14', '>=14'))
newdf$pre <- factor(newdf$pre, levels = c('<800', '800~1200', '1200~1600', '>=1600'))

```

```{R}
assogrids <- assogrids %>%
  dplyr::mutate(tempround = round(CHELSA_Annual_Mean_Temperature_mean, digits = -1),
         preround = round(CHELSA_Annual_Precipitation_mean, digits = -2))

assoround <- assogrids%>%
  group_by(tempround, preround)%>%
  summarize(meanasso = mean(assosimple),
            sdasso = sd(assosimple))%>%
  ungroup()


assoround %>%
  ggplot(., aes(x = tempround, y = preround, fill = meanasso))+
  geom_tile()+
  #geom_point(size = 2)+
  scale_fill_gradientn(colors = c('#0000ff', '#0074ff', '#0dffea', '#8cff41', '#ffdd00','#ff3700', '#c30000'), limits = c(-0.4,-0.1), oob = scales::squish)+
  theme_classic()+
  labs(x = 'Annual mean temperature', y = 'Annual precipitation')+
  theme(axis.title = element_text(color = '#000000', size = 20), axis.text = element_text(color = '#000000', size = 20))
  
assoround %>%
  ggplot(., aes(x = tempround, y = preround, fill = sdasso))+
  geom_tile()+
  #geom_point(size = 2)+
  scale_fill_gradientn(colors = c('#0000ff', '#0074ff', '#0dffea', '#8cff41', '#ffdd00','#ff3700', '#c30000'), limits = c(0,0.1), oob = scales::squish)+
  theme_classic()+
  labs(x = 'Annual mean temperature', y = 'Annual precipitation')+
  theme(axis.title = element_text(color = '#000000', size = 20), axis.text = element_text(color = '#000000', size = 20))
  

```

```{r}
assogrids %>%
  ggplot(., aes(x = CHELSA_Annual_Mean_Temperature_mean))+
  geom_histogram()


assogrids %>%
  ggplot(., aes(x = CHELSA_Annual_Precipitation_mean))+
  geom_histogram()

```

```{R}
assogrids<- assogrids%>%
  mutate(prelog = log10(CHELSA_Annual_Precipitation_mean),
         templog = log10(CHELSA_Annual_Mean_Temperature_mean))


assogrids <- assogrids %>%
  dplyr::mutate(tempround = round(CHELSA_Annual_Mean_Temperature_mean),
         preround = round(CHELSA_Annual_Precipitation_mean, digits = -2))

assoround <- assogrids%>%
  group_by(tempround, preround)%>%
  summarize(meanasso = mean(assosimple),
            sdasso = sd(assosimple))%>%
  ungroup()


assoround %>%
  ggplot(., aes(x = preround, y = tempround, fill = meanasso))+
  geom_tile()+
  #geom_point(size = 2)+
  scale_fill_gradientn(colors = c('#0000ff', '#0074ff', '#0dffea', '#8cff41', '#ffdd00','#ff3700', '#c30000'), limits = c(-0.4,-0.1), oob = scales::squish)+
  theme_classic()+
  labs(x = 'Annual precipitation', y = 'Annual mean temperature')+
  scale_x_continuous(trans = 'log10')+
  theme(axis.title = element_text(color = '#000000', size = 20), axis.text = element_text(color = '#000000', size = 20))
  


```




```{R}

hotdf <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 110)

colddf <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean<110)

summary(hotdf$CHELSA_Annual_Precipitation_mean)

summary(colddf$CHELSA_Annual_Precipitation_mean)

hot1 <- hotdf %>%
  filter(CHELSA_Annual_Precipitation_mean<800) %>%
  mutate(temp = 'hot', 
         pre = '<800')

hot2 <- hotdf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 800 & CHELSA_Annual_Precipitation_mean < 1200) %>%
  mutate(temp = 'hot',
         pre = '800~1200')

hot3 <- hotdf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1200 & CHELSA_Annual_Precipitation_mean < 1600) %>%
  mutate(temp = 'hot',
         pre = '1200~1600')

hot4 <- hotdf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1600) %>%
  mutate(temp = 'hot',
         pre = '>=1600')


cold1 <- colddf %>%
  filter(CHELSA_Annual_Precipitation_mean<800) %>%
  mutate(temp = 'cold',
         pre = '<800')

cold2 <- colddf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 800  & CHELSA_Annual_Precipitation_mean < 1200) %>%
  mutate(temp = 'cold',
         pre = '800~1200')

cold3 <- colddf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1200 & CHELSA_Annual_Precipitation_mean < 1600) %>%
  mutate(temp = 'cold',
         pre = '1200~1600')

cold4 <- colddf %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1600) %>%
  mutate(temp = 'cold',
         pre = '>=1600')



newdf <- rbind(hot1, hot2, hot3, hot4, cold1, cold2, cold3, cold4)

pres <- unique(newdf$pre)

newdf$pre <- factor(newdf$pre, levels = pres)

q3<-newdf %>%
  ggplot(., aes(x = pre, y = assosimple, color = temp))+
  stat_summary(fun.data = 'mean_cl_boot', size = 1.5)+
  stat_summary(fun = mean, geom = 'line', size = 1, aes(group = temp))+
  theme_classic()+
  geom_abline(slope = 0, intercept = 0,linetype = 'dashed')+
  labs(x = 'Annual precipitation', y = 'Grid-level\n negative association')+
  theme_classic()+
  scale_color_manual(values = c('#2166AC', '#B2182B'))+
  geom_abline(slope = 0, intercept = 0,linetype = 'dashed')+
  theme(axis.title = element_text(size = 20, color = '#000000'), axis.text = element_text(size = 20,color = '#000000'), legend.position = 'none', plot.margin = margin(1,1,1,1,unit = 'cm'))
  


```

```{R}

wetdf <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1000)

drydf <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean< 1000)

summary(wetdf$CHELSA_Annual_Mean_Temperature_mean)

summary(drydf$CHELSA_Annual_Mean_Temperature_mean)

wet1 <- wetdf %>%
  filter(CHELSA_Annual_Mean_Temperature_mean<60) %>%
  mutate(pre = 'wet', 
         temp = '<6')

wet2 <- wetdf %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 60 & CHELSA_Annual_Mean_Temperature_mean < 120) %>%
  mutate(temp = '6~12',
         pre = 'wet')

wet3 <- wetdf %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 120 & CHELSA_Annual_Mean_Temperature_mean < 180) %>%
  mutate(temp = '12~18',
         pre = 'wet')

wet4 <- wetdf %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 180) %>%
  mutate(temp = '>=18',
         pre = 'wet')


dry1 <- drydf %>%
  filter(CHELSA_Annual_Mean_Temperature_mean<60) %>%
  mutate(temp = '<6',
         pre = 'dry')

dry2 <- drydf %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 60  & CHELSA_Annual_Mean_Temperature_mean < 120) %>%
  mutate(temp = '6~12',
         pre = 'dry')

dry3 <- drydf %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 120 & CHELSA_Annual_Mean_Temperature_mean < 180) %>%
  mutate(temp = '12~18',
         pre = 'dry')

dry4 <- drydf %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 180) %>%
  mutate(temp = '>=18',
         pre = 'dry')



newdf <- rbind(wet1, wet2, wet3, wet4, dry1, dry2, dry3, dry4)
temps <- unique(newdf$temp)

newdf$temp <- factor(newdf$temp, levels = temps)

p4<-newdf %>%
  ggplot(., aes(x = temp, y = assosimple, color = pre))+
  stat_summary(fun.data = 'mean_cl_boot', size = 1.5)+
  stat_summary(fun = mean, geom = 'line', size = 1, aes(group = pre))+
  theme_classic()+
  geom_abline(slope = 0, intercept = 0,linetype = 'dashed')+
  labs(x = 'Annual mean temperature', y = 'Grid-level\n mean association')+
  #theme_classic()+
  scale_color_manual(values = c('#2166AC', '#B2182B'))+
  geom_abline(slope = 0, intercept = 0,linetype = 'dashed')+
  theme(axis.title = element_text(size = 20, color = '#000000'), axis.text = element_text(size = 20,color = '#000000'), legend.position = 'none', plot.margin = margin(1,1,1,1,unit = 'cm'))



newdf %>%
  ggplot(., aes(x = temp, y = assosimple, color = pre))+
  stat_summary(fun.data = 'mean_cl_boot', size = 1)+
  stat_summary(fun = mean, geom = 'line', size = 1, aes(group = pre))+
  theme_classic()+
  geom_abline(slope = 0, intercept = 0,linetype = 'dashed')


```

```{R}

assotree <- lmtree(assosimple~CHELSA_Annual_Mean_Temperature_mean | CHELSA_Annual_Precipitation_mean, maxdepth = 3, minsplit = 228, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = CHELSA_Annual_Mean_Temperature_mean,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               geom_point(aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assosimple), alpha = 0.1),
                               theme_classic()
 
                 )
  )

```

```{R}

summary(assogrids$CHELSA_Annual_Precipitation_mean)
summary(assogrids$CHELSA_Annual_Mean_Temperature_mean)

```

```{R}

library(lme4)

sub1 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean<500) %>%
  mutate(precate = '0~500')

#sub5 <- assogrids %>%
#  filter(CHELSA_Precipitation_of_Driest_Quarter_mean>=250 & CHELSA_Precipitation_of_Driest_Quarter_mean < 300) %>%
#  mutate(precate = "250~414")



sub2 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean>=500 & CHELSA_Annual_Precipitation_mean < 800) %>%
  mutate(precate = "500~800")

sub3 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean >= 800 & CHELSA_Annual_Precipitation_mean < 1100) %>%
  mutate(precate = "800~3400")

sub4 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1100 & CHELSA_Annual_Precipitation_mean < 1400) %>%
  mutate(precate = "800~3400")

sub5 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1050 & CHELSA_Annual_Precipitation_mean < 1250) %>%
  mutate(precate = "1050~1250")

sub6 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1400) %>%
  mutate(precate = '800~3400')


newdf <- rbind(sub1, sub2, sub3,sub4, sub6)
items <- unique(newdf$precate)

newdf$precate <- factor(newdf$precate, levels = items)

models <- lmList(scale(assosimple)~scale(CHELSA_Annual_Mean_Temperature_mean) | precate, data = newdf)

ss <- summary(models)

#items <- unique(newdf$precate)

coefs <- c(ss$coefficients[1,1,2], ss$coefficients[2,1,2], ss$coefficients[3,1,2])
coefs <- as.numeric(coefs)

stdrs <- c(ss$coefficients[1,2,2], ss$coefficients[2,2,2], ss$coefficients[3,2,2])

modeldf <- cbind(items, coefs, stdrs)



modeldf <- as.data.frame(modeldf)


modeldf$coefs <- coefs
modeldf$stdrs <- stdrs

modeldf$items <- factor(modeldf$items, levels = items)

p1<-ggplot(modeldf, aes(x = items, y = coefs, fill = coefs/abs(coefs)))+
  geom_point(size = 6.18, shape = 21)+
  geom_errorbar(aes(ymin = coefs - 2*stdrs, ymax = coefs + 2*stdrs), width = 0, size = 1)+
  geom_line(aes(group = coefs/coefs), color = '#000000', size = 1.5)+
  geom_hline(yintercept = 0, linetype = 'dashed')+
  labs(x = 'Annual precipitation', y = 'Grid-level\n mean association')+
  theme_classic()+
  scale_fill_gradient(low = '#000000', high = '#ffffff')+
  geom_abline(slope = 0, intercept = 0,linetype = 'dashed')+
  theme(axis.title = element_text(size = 20, color = '#000000'), axis.text = element_text(size = 20,color = '#000000'), legend.position = 'none', plot.margin = margin(1,1,1,1,unit = 'cm'))





```

```{R}

library(lme4)

sub1 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean<500) %>%
  mutate(precate = '0~500')

#sub5 <- assogrids %>%
#  filter(CHELSA_Precipitation_of_Driest_Quarter_mean>=250 & CHELSA_Precipitation_of_Driest_Quarter_mean < 300) %>%
#  mutate(precate = "250~414")



sub2 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean>=500 & CHELSA_Annual_Precipitation_mean < 750) %>%
  mutate(precate = "500~750")

sub3 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean >= 750 & CHELSA_Annual_Precipitation_mean < 1000) %>%
  mutate(precate = "750~1000")

sub4 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1000 & CHELSA_Annual_Precipitation_mean < 1250) %>%
  mutate(precate = "1000~1250")

sub5 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1100 & CHELSA_Annual_Precipitation_mean < 1300) %>%
  mutate(precate = "1100~1300")

sub6 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1250) %>%
  mutate(precate = '1250~3400')


newdf <- rbind(sub1, sub2, sub3,sub4,sub6)
items <- unique(newdf$precate)

newdf$precate <- factor(newdf$precate, levels = items)

models <- lmList(scale(asso)~scale(CHELSA_Annual_Mean_Temperature_mean) | precate, data = newdf)

ss <- summary(models)

#items <- unique(newdf$precate)

coefs <- c(ss$coefficients[1,1,2], ss$coefficients[2,1,2], ss$coefficients[3,1,2], ss$coefficients[4,1,2], ss$coefficients[5,1,2])
coefs <- as.numeric(coefs)

stdrs <- c(ss$coefficients[1,2,2], ss$coefficients[2,2,2], ss$coefficients[3,2,2], ss$coefficients[4,2,2], ss$coefficients[5,2,2])

modeldf <- cbind(items, coefs, stdrs)



modeldf <- as.data.frame(modeldf)


modeldf$coefs <- coefs
modeldf$stdrs <- stdrs

modeldf$items <- factor(modeldf$items, levels = items)

ggplot(modeldf, aes(x = items, y = coefs, fill = coefs/abs(coefs)))+
  geom_point(size = 6.18, shape = 21)+
  geom_errorbar(aes(ymin = coefs - 2*stdrs, ymax = coefs + 2*stdrs), width = 0, size = 1)+
  geom_line(aes(group = coefs/coefs), color = '#000000', size = 1.5)+
  geom_hline(yintercept = 0, linetype = 'dashed')+
  labs(x = 'Annual precipitation', y = 'Grid-level\n mean association')+
  theme_classic()+
  scale_fill_gradient(low = '#000000', high = '#ffffff')+
  geom_abline(slope = 0, intercept = 0,linetype = 'dashed')+
  theme(axis.title = element_text(size = 20, color = '#000000'), axis.text = element_text(size = 20,color = '#000000'), legend.position = 'none', plot.margin = margin(1,1,1,1,unit = 'cm'))
  



ggplot(sub1, aes(x = CHELSA_Annual_Mean_Temperature_mean, y = asso))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(sub2, aes(x = CHELSA_Annual_Mean_Temperature_mean, y = asso))+
  geom_point(alpha = 0.1)+
  geom_smooth()


ggplot(sub3, aes(x = CHELSA_Annual_Mean_Temperature_mean, y = asso))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(sub4, aes(x = CHELSA_Annual_Mean_Temperature_mean, y = asso))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(sub5, aes(x = CHELSA_Annual_Mean_Temperature_mean, y = asso))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(sub6, aes(x = CHELSA_Annual_Mean_Temperature_mean, y = asso))+
  geom_point(alpha = 0.1)+
  geom_smooth()

```

```{R}

library(lme4)

sub1 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean<600) %>%
  mutate(precate = '0~800')

#sub5 <- assogrids %>%
#  filter(CHELSA_Precipitation_of_Driest_Quarter_mean>=250 & CHELSA_Precipitation_of_Driest_Quarter_mean < 300) %>%
#  mutate(precate = "250~414")



sub2 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean>=600 & CHELSA_Annual_Precipitation_mean < 800) %>%
  mutate(precate = "0~800")

sub3 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean >= 800 & CHELSA_Annual_Precipitation_mean < 1000) %>%
  mutate(precate = "800~1200")

sub4 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1000 & CHELSA_Annual_Precipitation_mean < 1200) %>%
  mutate(precate = "800~1200")

sub5 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1100 & CHELSA_Annual_Precipitation_mean < 1300) %>%
  mutate(precate = "1100~1300")

sub6 <- assogrids %>%
  filter(CHELSA_Annual_Precipitation_mean >= 1200) %>%
  mutate(precate = '1200~3400')


newdf <- rbind(sub1, sub2, sub3,sub4,sub6)
items <- unique(newdf$precate)

newdf$precate <- factor(newdf$precate, levels = items)

models <- lmList(scale(assoneg)~scale(CHELSA_Annual_Mean_Temperature_mean) | precate, data = newdf)

ss <- summary(models)

#items <- unique(newdf$precate)

coefs <- c(ss$coefficients[1,1,2], ss$coefficients[2,1,2], ss$coefficients[3,1,2])
coefs <- as.numeric(coefs)

stdrs <- c(ss$coefficients[1,2,2], ss$coefficients[2,2,2], ss$coefficients[3,2,2])

modeldf <- cbind(items, coefs, stdrs)



modeldf <- as.data.frame(modeldf)


modeldf$coefs <- coefs
modeldf$stdrs <- stdrs

modeldf$items <- factor(modeldf$items, levels = items)

q1<-ggplot(modeldf, aes(x = items, y = coefs), fill = coefs/abs(coefs))+
  geom_point(size = 6.18, shape = 21)+
  geom_errorbar(aes(ymin = coefs - 2*stdrs, ymax = coefs + 2*stdrs), width = 0, size = 1)+
  geom_line(aes(group = coefs/coefs))+
  geom_hline(yintercept = 0, linetype = 'dashed')+
  labs(x = 'Annual precipitation', y = 'Grid-level\n negative association')+
  theme_classic()+
  scale_fill_gradient(low = '#000000', high = '#ffffff')+
  geom_abline(slope = 0, intercept = 0,linetype = 'dashed')+
  theme(axis.title = element_text(size = 20, color = '#000000'), axis.text = element_text(size = 20,color = '#000000'), legend.position = 'none', plot.margin = margin(1,1,1,1,unit = 'cm'))



ggplot(rbind(sub1, sub2), aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assoneg))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(sub2, aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assoneg))+
  geom_point(alpha = 0.1)+
  geom_smooth()


ggplot(rbind(sub3, sub4), aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assoneg))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(sub4, aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assoneg))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(sub5, aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assoneg))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(sub6, aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assoneg))+
  geom_point(alpha = 0.1)+
  geom_smooth()

```

```{R}

summary(assogrids$CHELSA_Annual_Mean_Temperature_mean)

```

```{R}

library(lme4)

sub1 <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean<0) %>%
  mutate(precate = '-6~6')

#sub5 <- assogrids %>%
#  filter(CHELSA_Precipitation_of_Driest_Quarter_mean>=250 & CHELSA_Precipitation_of_Driest_Quarter_mean < 300) %>%
#  mutate(precate = "250~414")



sub2 <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean>=0 & CHELSA_Annual_Mean_Temperature_mean < 60) %>%
  mutate(precate = "-6~6")

sub3 <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 60 & CHELSA_Annual_Mean_Temperature_mean < 120) %>%
  mutate(precate = "6~12")

sub4 <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 120 & CHELSA_Annual_Mean_Temperature_mean < 180) %>%
  mutate(precate = "12~18")

sub5 <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 120 & CHELSA_Annual_Mean_Temperature_mean < 140) %>%
  mutate(precate = "12~14")

sub6 <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 180) %>%
  mutate(precate = '18~24')


newdf <- rbind(sub1, sub2, sub3,sub4,  sub6)
items <- unique(newdf$precate)

newdf$precate <- factor(newdf$precate, levels = items)

models <- lmList(scale(asso)~scale(CHELSA_Annual_Precipitation_mean) | precate, data = newdf)

ss <- summary(models)

#items <- unique(newdf$precate)

coefs <- c(ss$coefficients[1,1,2], ss$coefficients[2,1,2], ss$coefficients[3,1,2], ss$coefficients[4,1,2])
coefs <- as.numeric(coefs)

stdrs <- c(ss$coefficients[1,2,2], ss$coefficients[2,2,2], ss$coefficients[3,2,2], ss$coefficients[4,2,2])

modeldf <- cbind(items, coefs, stdrs)



modeldf <- as.data.frame(modeldf)


modeldf$coefs <- coefs
modeldf$stdrs <- stdrs

modeldf$items <- factor(modeldf$items, levels = items)

p2<-ggplot(modeldf, aes(x = items, y = coefs, fill = coefs/abs(coefs)))+
  geom_point(size = 6.18, shape = 21)+
  geom_errorbar(aes(ymin = coefs - 2*stdrs, ymax = coefs + 2*stdrs), width = 0, size = 1)+
  geom_hline(yintercept = 0, linetype = 'dashed')+
  geom_line(aes(group = coefs/coefs))+
  labs(x = 'Annual mean temperature', y = 'Grid-level\n mean association')+
  theme_classic()+
  scale_fill_gradient(low = '#000000', high = '#ffffff')+
  geom_abline(slope = 0, intercept = 0,linetype = 'dashed')+
  theme(axis.title = element_text(size = 20, color = '#000000'), axis.text = element_text(size = 20,color = '#000000'), legend.position = 'none', plot.margin = margin(1,1,1,1,unit = 'cm'))



ggplot(sub1, aes(x = CHELSA_Annual_Precipitation_mean, y = asso))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(sub2, aes(x = CHELSA_Annual_Precipitation_mean, y = asso))+
  geom_point(alpha = 0.1)+
  geom_smooth()


ggplot(sub3, aes(x = CHELSA_Annual_Precipitation_mean, y = asso))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(sub4, aes(x = CHELSA_Annual_Precipitation_mean, y = asso))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(sub5, aes(x = CHELSA_Annual_Precipitation_mean, y = asso))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(sub6, aes(x = CHELSA_Annual_Precipitation_mean, y = asso))+
  geom_point(alpha = 0.1)+
  geom_smooth()

```

```{R}

library(lme4)

sub1 <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean<0) %>%
  mutate(precate = '-6~8')

#sub5 <- assogrids %>%
#  filter(CHELSA_Precipitation_of_Driest_Quarter_mean>=250 & CHELSA_Precipitation_of_Driest_Quarter_mean < 300) %>%
#  mutate(precate = "250~414")



sub2 <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean>=0 & CHELSA_Annual_Mean_Temperature_mean < 80) %>%
  mutate(precate = "-6~8")

sub3 <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 80 & CHELSA_Annual_Mean_Temperature_mean < 180) %>%
  mutate(precate = "8~18")

sub4 <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 100 & CHELSA_Annual_Mean_Temperature_mean < 150) %>%
  mutate(precate = "10~15")

sub5 <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 150 & CHELSA_Annual_Mean_Temperature_mean < 200) %>%
  mutate(precate = "15~20")

sub6 <- assogrids %>%
  filter(CHELSA_Annual_Mean_Temperature_mean >= 180) %>%
  mutate(precate = '18~24')


newdf <- rbind(sub1, sub2, sub3,sub6)
items <- unique(newdf$precate)

newdf$precate <- factor(newdf$precate, levels = items)

models <- lmList(scale(assoneg)~scale(CHELSA_Annual_Precipitation_mean) | precate, data = newdf)

ss <- summary(models)

#items <- unique(newdf$precate)

coefs <- c(ss$coefficients[1,1,2], ss$coefficients[2,1,2], ss$coefficients[3,1,2])
coefs <- as.numeric(coefs)

stdrs <- c(ss$coefficients[1,2,2], ss$coefficients[2,2,2], ss$coefficients[3,2,2])

modeldf <- cbind(items, coefs, stdrs)



modeldf <- as.data.frame(modeldf)


modeldf$coefs <- coefs
modeldf$stdrs <- stdrs

modeldf$items <- factor(modeldf$items, levels = items)

q2<-ggplot(modeldf, aes(x = items, y = coefs, fill = coefs/abs(coefs)))+
  geom_point(size = 6.18, shape = 21)+
  geom_errorbar(aes(ymin = coefs - 2*stdrs, ymax = coefs + 2*stdrs), width = 0, size = 1)+
  geom_line(aes(group = coefs/coefs))+
  geom_hline(yintercept = 0, linetype = 'dashed')+
  labs(x = 'Annual mean temperature', y = 'Grid-level\n negative association')+
  theme_classic()+
  scale_fill_gradient(low = '#000000', high = '#ffffff')+
  geom_abline(slope = 0, intercept = 0,linetype = 'dashed')+
  theme(axis.title = element_text(size = 20, color = '#000000'), axis.text = element_text(size = 20,color = '#000000'), legend.position = 'none', plot.margin = margin(1,1,1,1,unit = 'cm'))



ggplot(rbind(sub1, sub2), aes(x = CHELSA_Annual_Precipitation_mean, y = assoneg))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(sub2, aes(x = CHELSA_Annual_Precipitation_mean, y = assoneg))+
  geom_point(alpha = 0.1)+
  geom_smooth()


ggplot(sub3, aes(x = CHELSA_Annual_Precipitation_mean, y = assoneg))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(rbind(sub4, sub6), aes(x = CHELSA_Annual_Precipitation_mean, y = assoneg))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(sub5, aes(x = CHELSA_Annual_Precipitation_mean, y = assoneg))+
  geom_point(alpha = 0.1)+
  geom_smooth()

ggplot(sub6, aes(x = CHELSA_Annual_Precipitation_mean, y = assoneg))+
  geom_point(alpha = 0.1)+
  geom_smooth()

```

```{R}

"library(ggpubr)

ggarrange(p1,p2,p3,
          q1,q2,q3,
          nrow = 2,
          ncol = 3)"



```

```{R}

"ggarrange(p1,q1,
          p2,q2,
          p3,q3,
          nrow = 3,
          ncol = 2,
          labels = c('A', 'B',
                     'C', 'D',
                     'E', 'F'),
          font.label = list(size = 20))
"
```

```{R}

library(ggpubr)

ggarrange(p3,p4,
          nrow = 2,
          ncol = 1,
          labels = c('A', 'B'))


```

```{r}

stdbands <- assogrids %>%
  dplyr::select(c(
    CHELSA_Annual_Mean_Temperature_std,
    CHELSA_Annual_Precipitation_std,
    height_std,
    stddensity,
    CHELSA_Temperature_Annual_Range_std
  ))


stdpca <- prcomp(stdbands, center = T, scale.=T)

summary(stdpca)

#humanmatrix <- humanpca$x

#humanmatrix <- as.data.frame(humanmatrix)

#names(humanmatrix) <- c('humanpc1', 'humanpc2', 'humanpc3'
                      #'humanpc4'
                      #'humanpc5','humanpc6'
 #                     )

stdpca$rotation

stdmatrix <- stdpca$x

stdmatrix <- as.data.frame(stdmatrix)

names(stdmatrix) <- c('stdpc1', 'stdpc2', 'stdpc3', 'stdpc4', 'stdpc5')

assogrids <- cbind(assogrids, stdmatrix)

```
```{r}
library(HH)

vif(stdbands)

vif(stdmatrix)


```


```{R}

library(partykit)

library(ggparty)

set.seed(100)

assotree <- ctree(assosimple~  height_std + stddensity + CHELSA_Annual_Mean_Temperature_std + CHELSA_Annual_Precipitation_std + CHELSA_Temperature_Annual_Range_std, mtry = 2, maxdepth = 3, minbucket = 260, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_boxplot(aes(x = '', y = assosimple), outlier.shape = NA),
                               coord_cartesian(ylim = c(-0.6,0.1)),
                               #geom_point(aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assosimple), alpha = 0.1),
                               theme_classic()
 
                 )
  )

```


```{R}
set.seed(1024)

assotree <- ctree(assosimple ~ height_mean + meandensity + CHELSA_Annual_Mean_Temperature_mean + CHELSA_Annual_Precipitation_mean + CHELSA_Temperature_Annual_Range_mean + regionalrichness, mtry = 2, maxdepth = 3, minbucket = 260, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_boxplot(aes(x = '', y = assosimple), outlier.shape = NA),
                               coord_cartesian(ylim = c(-0.5,0.1)),
                               #geom_point(aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assosimple), alpha = 0.1),
                               theme_classic()
 
                 )
  )

```

```{R}
set.seed(1024)

assotree <- ctree(assosimple ~ height_mean + meandensity + CHELSA_Annual_Mean_Temperature_mean + CHELSA_Annual_Precipitation_mean + CHELSA_Temperature_Annual_Range_mean + regionalrichness + height_std + stddensity + CHELSA_Annual_Mean_Temperature_std + CHELSA_Annual_Precipitation_std + CHELSA_Temperature_Annual_Range_std, mtry = 3, maxdepth = 3, minbucket = 260, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_boxplot(aes(x = '', y = assosimple), outlier.shape = NA),
                               coord_cartesian(ylim = c(-0.5,0.1)),
                               #geom_point(aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assosimple), alpha = 0.1),
                               theme_classic()
 
                 )
  )

```

```{R}
set.seed(0)

dens_df <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())



assotree <- ctree(assosimple~  stdpc1 + stdpc2 + stdpc3 + stdpc4 + stdpc5, mtry = 2, maxdepth = 3, minbucket = 260, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_boxplot(aes(x = '', y = assosimple), outlier.shape = NA),
                               #geom_point(aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assosimple), alpha = 0.1),
                               theme_classic()
 
                 )
  )

```


```{r}
set.seed(1000)

dens_df1 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df2 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df3 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

assotree <- lmtree(assosimple~ CHELSA_Annual_Mean_Temperature_std | CHELSA_Annual_Mean_Temperature_mean + CHELSA_Annual_Precipitation_mean + regionalrichness, mtry = 2, maxdepth = 3, minsize = 260, data = assogrids)


print(assotree)


dens_df1 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df2 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())


xdens = density(assotree[1]$data$regionalrichness)$x
ydens = density(assotree[1]$data$regionalrichness)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 7] <- 'right'

dens_df1 <- rbind(dens_df1, data.frame(xdens, ydens, 1, breaks))


xdens = density(assotree[3]$data$regionalrichness)$x
ydens = density(assotree[3]$data$regionalrichness)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 30] <- 'right'

dens_df2 <- rbind(dens_df2, data.frame(xdens, ydens, 2, breaks))

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(ids = 1, 
                 gglist = list(geom_ribbon(data = dens_df1,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                               alpha = 0.8),
                 xlab('Species richness'),
                 theme_bw(),
                 theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 0.5)+
  geom_node_plot(ids = 3,
                 gglist = list(geom_ribbon(data = dens_df2,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                                           alpha = 0.8
                                           ),
                               xlab('Species richness'),
                               theme_bw(),
                               theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 0.5
                               
                               )+
  
      
               
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = CHELSA_Annual_Mean_Temperature_std,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               geom_point(aes(x = CHELSA_Annual_Mean_Temperature_std, y = assosimple), alpha = 0.1),
                               #scale_x_continuous(trans = 'log1p'),
                               theme_classic()
 
                 )
  )

```
```{r}
set.seed(1000)

dens_df1 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df2 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df3 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

assotree <- lmtree(assosimple~ CHELSA_Annual_Precipitation_std | CHELSA_Annual_Mean_Temperature_mean + CHELSA_Annual_Precipitation_mean + regionalrichness, mtry = 2, maxdepth = 3, minsize = 260, data = assogrids)


print(assotree)

xdens = density(assotree[1]$data$regionalrichness)$x
ydens = density(assotree[1]$data$regionalrichness)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 7] <- 'right'

dens_df1 <- rbind(dens_df1, data.frame(xdens, ydens, 1, breaks))


xdens = density(assotree[3]$data$regionalrichness)$x
ydens = density(assotree[3]$data$regionalrichness)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 31] <- 'right'

dens_df2 <- rbind(dens_df2, data.frame(xdens, ydens, 3, breaks))

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(ids = 1, 
                 gglist = list(geom_ribbon(data = dens_df1,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                               alpha = 0.8),
                 xlab('Species richness'),
                 theme_bw(),
                 theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 0.5)+
  geom_node_plot(ids = 3,
                 gglist = list(geom_ribbon(data = dens_df2,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                                           alpha = 0.8
                                           ),
                               xlab('Species richness'),
                               theme_bw(),
                               theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 0.5
                               
                               )+
  
      
               
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = CHELSA_Annual_Precipitation_std,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               geom_point(aes(x = CHELSA_Annual_Precipitation_std, y = assosimple), alpha = 0.1),
                               scale_x_continuous(trans = 'log10'),
                               theme_classic()
 
                 )
  )

```

```{r}
set.seed(5000)

dens_df1 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df2 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df3 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

assotree <- lmtree(assosimple~ CHELSA_Annual_Precipitation_mean | CHELSA_Annual_Mean_Temperature_mean + regionalrichness + height_mean + meandensity, mtry = 2,maxdepth = 3, minsize = 260, data = assogrids)


print(assotree)

dens_df1 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df2 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df3 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

xdens = density(assotree[1]$data$CHELSA_Annual_Mean_Temperature_mean)$x
ydens = density(assotree[1]$data$CHELSA_Annual_Mean_Temperature_mean)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 73.66] <- 'right'

dens_df1 <- rbind(dens_df1, data.frame(xdens, ydens, 1, breaks))


xdens = density(assotree[2]$data$CHELSA_Annual_Mean_Temperature_mean)$x
ydens = density(assotree[2]$data$CHELSA_Annual_Mean_Temperature_mean)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 46.89] <- 'right'

dens_df2 <- rbind(dens_df2, data.frame(xdens, ydens, 2, breaks))


xdens = density(assotree[5]$data$regionalrichness)$x
ydens = density(assotree[5]$data$regionalrichness)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 9] <- 'right'

dens_df3 <- rbind(dens_df3, data.frame(xdens, ydens, 5, breaks))

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(ids = 1, 
                 gglist = list(geom_ribbon(data = dens_df1,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                               alpha = 0.8),
                 xlab('Annual mean temperature'),
                 theme_bw(),
                 theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 0.5)+
  geom_node_plot(ids = 2,
                 gglist = list(geom_ribbon(data = dens_df2,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                                           alpha = 0.8
                                           ),
                               xlab('Annual mean temperature'),
                               theme_bw(),
                               theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 0.5
                               
                               )+
  
      geom_node_plot(ids = 5,
                 gglist = list(geom_ribbon(data = dens_df3,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                                           alpha = 0.8
                                           ),
                               xlab('regionalrichness'),
                               theme_bw(),
                               theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 0.5
                               
                               )+
               
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = CHELSA_Annual_Precipitation_mean,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               geom_point(aes(x = CHELSA_Annual_Precipitation_mean, y = assosimple), alpha = 0.1),
                               scale_x_continuous(trans = 'log10'),
                               theme_classic()
 
                 )
  )


```
```{r}
set.seed(100)

dens_df1 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df2 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df3 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

assotree <- lmtree(assosimple~ CHELSA_Annual_Mean_Temperature_mean | CHELSA_Annual_Precipitation_mean + regionalrichness + height_mean + meandensity, mtry = 2,maxdepth = 3, minsize = 260, data = assogrids)


print(assotree)

dens_df1 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df2 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

#dens_df3 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

xdens = density(assotree[1]$data$regionalrichness)$x
ydens = density(assotree[1]$data$regionalrichness)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 7] <- 'right'

dens_df1 <- rbind(dens_df1, data.frame(xdens, ydens, 1, breaks))


xdens = density(assotree[3]$data$regionalrichness)$x
ydens = density(assotree[3]$data$regionalrichness)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 28] <- 'right'

dens_df2 <- rbind(dens_df2, data.frame(xdens, ydens, 3, breaks))

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(ids = 1, 
                 gglist = list(geom_ribbon(data = dens_df1,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                               alpha = 0.8),
                 xlab('Species richness'),
                 theme_bw(),
                 theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 0.5)+
  geom_node_plot(ids = 3,
                 gglist = list(geom_ribbon(data = dens_df2,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                                           alpha = 0.8
                                           ),
                               xlab('Species richness'),
                               theme_bw(),
                               theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 0.5
                               
                               )+
  
               
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = CHELSA_Annual_Mean_Temperature_mean,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               geom_point(aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assosimple), alpha = 0.1),
                               theme_classic()
 
                 )
  )
```




```{R}
set.seed(1000)

dens_df1 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df2 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df3 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

assotree <- lmtree(assosimple~ CHELSA_Annual_Mean_Temperature_mean | height_std + stddensity + CHELSA_Annual_Mean_Temperature_std + CHELSA_Annual_Precipitation_std + CHELSA_Temperature_Annual_Range_std, mtry = 2, maxdepth = 3, minsize = 260, data = assogrids)


print(assotree)

xdens = density(assotree[1]$data$CHELSA_Annual_Mean_Temperature_std)$x
ydens = density(assotree[1]$data$CHELSA_Annual_Mean_Temperature_std)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 3.43] <- 'right'

dens_df1 <- rbind(dens_df1, data.frame(xdens, ydens, 1, breaks))


xdens = density(assotree[2]$data$CHELSA_Annual_Precipitation_std)$x
ydens = density(assotree[2]$data$CHELSA_Annual_Precipitation_std)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 39.52] <- 'right'

dens_df2 <- rbind(dens_df2, data.frame(xdens, ydens, 2, breaks))


xdens = density(assotree[5]$data$CHELSA_Annual_Mean_Temperature_std)$x
ydens = density(assotree[5]$data$CHELSA_Annual_Mean_Temperature_std)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 16.64] <- 'right'

dens_df3 <- rbind(dens_df3, data.frame(xdens, ydens, 5, breaks))


rp2<- ggparty(assotree, terminal_space = 0.55)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(ids = 1, 
                 gglist = list(geom_ribbon(data = dens_df1,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                               alpha = 0.8),
                 xlab('Annual mean temperature std'),
                 theme_classic(),
                 theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 1)+
  geom_node_plot(ids = 2,
                 gglist = list(geom_ribbon(data = dens_df2,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                                           alpha = 0.8
                                           ),
                               xlab('Annual precipitation std'),
                               theme_classic(),
                               theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 1
                               
                               )+
  
      geom_node_plot(ids = 5,
                 gglist = list(geom_ribbon(data = dens_df3,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                                           alpha = 0.8
                                           ),
                               xlab('Annual mean temperature std'),
                               theme_classic(),
                               theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 1
                               
                               )+
               
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = CHELSA_Annual_Mean_Temperature_mean,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               #geom_point(aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assosimple), alpha = 0.1),
                               theme_classic()
 
                 ),
                 height = 0.5,
                 size = 1
  )

```

```{R}
set.seed(1000)

assotree <- lmtree(assosimple~ CHELSA_Annual_Mean_Temperature_mean | stdpc1+ stdpc2 + stdpc3 + stdpc4 + stdpc5, mtry = 2, maxdepth = 3, minsize = 260, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = CHELSA_Annual_Mean_Temperature_mean,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               geom_point(aes(x = CHELSA_Annual_Mean_Temperature_mean, y = assosimple), alpha = 0.1),
                               theme_classic()
 
                 )
  )

```



```{R}
set.seed(1000)

assotree <- lmtree(assosimple~ regionalrichness | height_std + stddensity + CHELSA_Annual_Mean_Temperature_std + CHELSA_Annual_Precipitation_std + CHELSA_Temperature_Annual_Range_std, mtry = 2, maxdepth = 3, minsize = 260, data = assogrids)

print(assotree)

dens_df1 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df2 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df3 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

xdens = density(assotree[1]$data$CHELSA_Annual_Precipitation_std)$x
ydens = density(assotree[1]$data$CHELSA_Annual_Precipitation_std)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 60.27] <- 'right'

dens_df1 <- rbind(dens_df1, data.frame(xdens, ydens, 1, breaks))


xdens = density(assotree[2]$data$CHELSA_Annual_Mean_Temperature_std)$x
ydens = density(assotree[2]$data$CHELSA_Annual_Mean_Temperature_std)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 3.4] <- 'right'

dens_df2 <- rbind(dens_df2, data.frame(xdens, ydens, 2, breaks))


xdens = density(assotree[5]$data$CHELSA_Annual_Mean_Temperature_std)$x
ydens = density(assotree[5]$data$CHELSA_Annual_Mean_Temperature_std)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 2.32] <- 'right'

dens_df3 <- rbind(dens_df3, data.frame(xdens, ydens, 5, breaks))


rp1<-ggparty(assotree, terminal_space = 0.55)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(ids = 1, 
                 gglist = list(geom_ribbon(data = dens_df1,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                               alpha = 0.8),
                 xlab('Annual precipitation std'),
                 theme_classic(),
                 theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 1)+
  geom_node_plot(ids = 2,
                 gglist = list(geom_ribbon(data = dens_df2,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                                           alpha = 0.8
                                           ),
                               xlab('Annual mean temperature std'),
                               theme_classic(),
                               theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 1
                               
                               )+
  
      geom_node_plot(ids = 5,
                 gglist = list(geom_ribbon(data = dens_df3,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                                           alpha = 0.8
                                           ),
                               xlab('Annual mean temperature std'),
                               theme_classic(),
                               theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 1
                               
                               )+
               
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = regionalrichness,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               #geom_point(aes(x = regionalrichness, y = assosimple), alpha = 0.1),
                               scale_x_continuous(trans = 'log10'),
                               theme_classic()
 
                 ),
                 height = 0.5,
                 size = 1
  )

```

```{R}
set.seed(0)

assotree <- lmtree(assosimple~ regionalrichness | stdpc1 + stdpc2+stdpc3+stdpc4+stdpc5, mtry = 2, maxdepth = 3, minsize = 260, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = regionalrichness,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               geom_point(aes(x = regionalrichness, y = assosimple), alpha = 0.1),
                               scale_x_continuous(trans = 'log10'),
                               theme_classic()
 
                 )
  )

```




```{R}


set.seed(1000)
assotree <- lmtree(assosimple~ CHELSA_Annual_Precipitation_mean | height_std + stddensity + CHELSA_Annual_Mean_Temperature_std + CHELSA_Annual_Precipitation_std + CHELSA_Temperature_Annual_Range_std, mtry = 2, maxdepth = 3, minsize = 260, data = assogrids)

print(assotree)

dens_df1 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df2 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

dens_df3 <- data.frame(x_dens = numeric(), y_dens = numeric(), id = numeric(), breaks = character())

xdens = density(assotree[1]$data$CHELSA_Annual_Precipitation_std)$x
ydens = density(assotree[1]$data$CHELSA_Annual_Precipitation_std)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 155.55] <- 'right'

dens_df1 <- rbind(dens_df1, data.frame(xdens, ydens, 1, breaks))


xdens = density(assotree[2]$data$CHELSA_Annual_Precipitation_std)$x
ydens = density(assotree[2]$data$CHELSA_Annual_Precipitation_std)$y
breaks <- rep('left', length(xdens))
breaks[xdens > 60.37] <- 'right'

dens_df2 <- rbind(dens_df2, data.frame(xdens, ydens, 2, breaks))


#xdens = density(assotree[4]$data$CHELSA_Annual_Precipitation_std)$x
#ydens = density(assotree[4]$data$CHELSA_Annual_Precipitation_std)$y
#breaks <- rep('left', length(xdens))
#breaks[xdens > 2.32] <- 'right'

#dens_df3 <- rbind(dens_df3, data.frame(xdens, ydens, 5, breaks))


rp3<-ggparty(assotree, terminal_space = 0.55)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(ids = 1, 
                 gglist = list(geom_ribbon(data = dens_df1,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                               alpha = 0.8),
                 xlab('Annual precipitation std'),
                 theme_classic(),
                 theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 0.5)+
  geom_node_plot(ids = 2,
                 gglist = list(geom_ribbon(data = dens_df2,
                                           aes(x = xdens,
                                               ymin = 0,
                                               ymax = ydens,
                                               fill = breaks),
                                           show.legend = FALSE,
                                           alpha = 0.8
                                           ),
                               xlab('Annual precipitation std'),
                               theme_classic(),
                               theme(axis.title.y = element_blank())),
                 size = 1.5,
                 height = 0.5
                               
                               )+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = CHELSA_Annual_Precipitation_mean,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               #geom_point(aes(x = CHELSA_Annual_Precipitation_mean, y = assosimple), alpha = 0.1),
                               scale_x_continuous(trans = 'log10'),
                               theme_classic()
 
                 ),
                 height = 0.5,
                 size = 1
  )

```


```{r}

library(ggpubr)

ggarrange(rp1,
          rp2,
          rp3,
          labels = c("A", "B", "C"),
          nrow = 3)

```




```{R}


set.seed(0)
assotree <- lmtree(assosimple~ CHELSA_Annual_Precipitation_mean | stdpc1 + stdpc2 + stdpc3 + stdpc4 + stdpc5, mtry = 2, maxdepth = 3, minsize = 260, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = CHELSA_Annual_Precipitation_mean,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               geom_point(aes(x = CHELSA_Annual_Precipitation_mean, y = assosimple), alpha = 0.1),
                               scale_x_continuous(trans = 'log10'),
                               theme_classic()
 
                 )
  )

```




```{R}

set.seed(0)

assotree <- lmtree(assosimple~ height_mean | height_std + stddensity + CHELSA_Annual_Mean_Temperature_std + CHELSA_Annual_Precipitation_std + CHELSA_Temperature_Annual_Range_std, mtry = 2, maxdepth = 3, minsize = 260, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = height_mean,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               geom_point(aes(x = height_mean, y = assosimple), alpha = 0.1),
                               #scale_x_continuous(trans = 'log10'),
                               theme_classic()
 
                 )
  )

```

```{R}

set.seed(0)

assotree <- lmtree(assosimple~ height_mean | stdpc1 + stdpc2 + stdpc3 + stdpc4+ stdpc5, mtry = 2, maxdepth = 3, minsize = 260, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = height_mean,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               geom_point(aes(x = height_mean, y = assosimple), alpha = 0.1),
                               #scale_x_continuous(trans = 'log10'),
                               theme_classic()
 
                 )
  )

```



```{R}

set.seed(0)
assotree <- lmtree(assosimple~ meandensity | height_std + stddensity + CHELSA_Annual_Mean_Temperature_std + CHELSA_Annual_Precipitation_std + CHELSA_Temperature_Annual_Range_std, mtry = 2, maxdepth = 3, minsize = 260, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = meandensity,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               geom_point(aes(x = meandensity, y = assosimple), alpha = 0.1),
                               scale_x_continuous(trans = 'log10'),
                               theme_classic()
 
                 )
  )

```

```{R}

set.seed(0)
assotree <- lmtree(assosimple~ meandensity | stdpc1 + stdpc2 + stdpc3 + stdpc4 + stdpc5, mtry = 2, maxdepth = 3, minsize = 260, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = meandensity,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               geom_point(aes(x = meandensity, y = assosimple), alpha = 0.1),
                               scale_x_continuous(trans = 'log10'),
                               theme_classic()
 
                 )
  )

```



```{R}

set.seed(0)
assotree <- lmtree(assosimple~ CHELSA_Temperature_Annual_Range_mean | height_std + stddensity + CHELSA_Annual_Mean_Temperature_std + CHELSA_Annual_Precipitation_std + CHELSA_Temperature_Annual_Range_std, mtry = 2, maxdepth = 3, minsize = 260, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = CHELSA_Temperature_Annual_Range_mean,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               geom_point(aes(x = CHELSA_Temperature_Annual_Range_mean, y = assosimple), alpha = 0.1),
                               #scale_x_continuous(trans = 'log10'),
                               theme_classic()
 
                 )
  )

```

```{R}

set.seed(0)
assotree <- lmtree(assosimple~ CHELSA_Temperature_Annual_Range_mean | stdpc1 + stdpc2 + stdpc3 + stdpc4 + stdpc5, mtry = 2, maxdepth = 3, minsize = 260, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = CHELSA_Temperature_Annual_Range_mean,
                                               y = assosimple),
                                           method = 'lm',color = 'blue', span = 1),
                               geom_point(aes(x = CHELSA_Temperature_Annual_Range_mean, y = assosimple), alpha = 0.1),
                               #scale_x_continuous(trans = 'log10'),
                               theme_classic()
 
                 )
  )

```



```{R}

assotree <- lmtree(asso~CHELSA_Precipitation_of_Driest_Quarter_mean | CHELSA_Annual_Mean_Temperature_mean, maxdepth = 4, minsplit = 225, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = CHELSA_Precipitation_of_Driest_Quarter_mean,
                                               y = asso),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = CHELSA_Precipitation_of_Driest_Quarter_mean, y = asso), alpha = 0.1),
                               theme_classic()
 
                 )
  )

```

```{R}

assotree <- lmtree(assoneg~CHELSA_Precipitation_of_Driest_Quarter_mean | CHELSA_Annual_Mean_Temperature_mean, maxdepth = 4, minsplit = 225, data = assogrids)

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = CHELSA_Precipitation_of_Driest_Quarter_mean,
                                               y = assoneg),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = CHELSA_Precipitation_of_Driest_Quarter_mean, y = assoneg), alpha = 0.1),
                               theme_classic()
 
                 )
  )

```

################################################################################################## 

```{R}

assotree <- lmtree(richnessresidual~assoresidual | CHELSA_Annual_Mean_Temperature_mean, maxdepth = 3, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = assoresidual,
                                               y = richnessresidual),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = assoresidual, y = richnessresidual), alpha = 0.1),
                               theme_classic()
 
                 )
  )

```

```{R}

assotree <- lmtree(richnessresidual~assoresidual | cnRatio_mean, maxdepth = 3, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = assoresidual,
                                               y = richnessresidual),
                                           method = 'loess',color = 'blue', span = 10),
                               geom_point(aes(x = assoresidual, y = richnessresidual), alpha = 0.1),
                               theme_classic()
                               
 
                 )
  )

```

```{R}

assotree <- lmtree(regionalrichness~asso | CHELSA_Precipitation_of_Driest_Quarter_mean, maxdepth = 3, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = asso,
                                               y = regionalrichness),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = asso, y = regionalrichness), alpha = 0.1)
 
                 )
  )

```

```{R}

assotree <- lmtree(regionalrichness~asso | PresentTreeCover_mean, maxdepth = 3, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = asso,
                                               y = regionalrichness),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = asso, y = regionalrichness), alpha = 0.1)
 
                 )
  )

```

```{R}

assotree <- lmtree(richnessresidual~assoresidual | CHELSA_Annual_Mean_Temperature_mean + CHELSA_Precipitation_of_Driest_Quarter_mean + cnRatio_mean + PresentTreeCover_mean + CanopyHeight_mean, maxdepth = 3, mtry = 4, minsplit = 440, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = assoresidual,
                                               y = richnessresidual),
                                           method = 'loess',color = 'blue', span = 10),
                               geom_point(aes(x = assoresidual, y = richnessresidual), alpha = 0.1),
                               theme_classic()
 
                 )
  )

```

################################################################################################################################### 

```{R}

assotree <- lmtree(regionalrichness~assoneg | regionaldensity, maxdepth = 3, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = assoneg,
                                               y = regionalrichness),
                                           method = 'loess',color = 'blue', span = 1.2),
                               geom_point(aes(x = assoneg, y = regionalrichness), alpha = 0.1)
 
                 )
  )

```

```{R}

assotree <- lmtree(richnessresidual~assonegresidual | CHELSA_Annual_Mean_Temperature_mean, maxdepth = 3, minsplit = 500, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = assonegresidual,
                                               y = richnessresidual),
                                           method = 'loess',color = 'blue', span = 1.2),
                               geom_point(aes(x = assonegresidual, y = richnessresidual), alpha = 0.1)
 
                 )
  )

```

```{R}

assotree <- lmtree(regionalrichness~assoneg | cnRatio_mean, maxdepth = 3, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = assoneg,
                                               y = regionalrichness),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = assoneg, y = regionalrichness), alpha = 0.1)
 
                 )
  )

```

```{R}

assotree <- lmtree(regionalrichness~assoneg | PresentTreeCover_mean, maxdepth = 3, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = assoneg,
                                               y = regionalrichness),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = assoneg, y = regionalrichness), alpha = 0.1))
 
                 
  )

```

```{R}

assotree <- lmtree(richnessresidual~assonegresidual | CHELSA_Annual_Mean_Temperature_mean + CHELSA_Precipitation_of_Driest_Quarter_mean + cnRatio_mean + PresentTreeCover_mean+CanopyHeight_mean, maxdepth = 3, mtry = 5, minsplit = 225, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = assonegresidual,
                                               y = richnessresidual),
                                           method = 'loess',color = 'blue', span = 10),
                               geom_point(aes(x = assonegresidual, y = richnessresidual), alpha = 0.1),
                               theme_classic()
 
                 )
  )

```

################################################################################################################################################################## 

```{R}

assotree <- lmtree(npp_mean~asso | PresentTreeCover_mean, maxdepth = 3, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = asso,
                                               y = npp_mean),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = asso, y = npp_mean), alpha = 0.1))
 
                 )


```

```{R}

assotree <- lmtree(npp_mean~asso | CHELSA_Annual_Mean_Temperature_mean, maxdepth = 3, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = asso,
                                               y = npp_mean),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = asso, y = npp_mean), alpha = 0.1))
 
                 )


```

```{R}

assotree <- lmtree(npp_mean~asso | CHELSA_Annual_Precipitation_mean, maxdepth = 3, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = asso,
                                               y = npp_mean),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = asso, y = npp_mean), alpha = 0.1))
 
                 )


```

```{R}

assotree <- lmtree(npp_mean~asso | cnRatio_mean, maxdepth = 3, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = asso,
                                               y = npp_mean),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = asso, y = npp_mean), alpha = 0.1)
  )
 
                 )


```

```{R}

assotree <- lmtree(nppresidual~assoresidual | CHELSA_Annual_Mean_Temperature_mean + CHELSA_Precipitation_of_Driest_Quarter_mean + cnRatio_mean +  PresentTreeCover_mean + CanopyHeight_mean, maxdepth = 3, mtry = 4, minsplit = 300, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = assoresidual,
                                               y = nppresidual),
                                           method = 'loess',color = 'blue', span = 10),
                               geom_point(aes(x = assoresidual, y = nppresidual), alpha = 0.1),
                               theme_classic()
 
                 )
  )

```

################################################################################################################################## 

```{R}

assotree <- lmtree(npp_mean~assoneg | PresentTreeCover_mean, maxdepth = 3, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = assoneg,
                                               y = npp_mean),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = assoneg, y = npp_mean), alpha = 0.1)
  )
 
                 )


```

```{R}

assotree <- lmtree(npp_mean~assoneg | CHELSA_Annual_Mean_Temperature_mean, maxdepth = 3, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = assoneg,
                                               y = npp_mean),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = assoneg, y = npp_mean), alpha = 0.1))
 
                 )


```

```{R}

assotree <- lmtree(npp_mean~assoneg | CHELSA_Annual_Precipitation_mean, maxdepth = 3, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = assoneg,
                                               y = npp_mean),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = assoneg, y = npp_mean), alpha = 0.1))
 
                 )


```

```{R}

assotree <- lmtree(npp_mean~assoneg | cnRatio_mean, maxdepth = 3, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = assoneg,
                                               y = npp_mean),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = assoneg, y = npp_mean), alpha = 0.1))
 
                 )


```

```{R}

assotree <- lmtree(nppresidual~assonegresidual | CHELSA_Annual_Mean_Temperature_mean + CHELSA_Precipitation_of_Driest_Quarter_mean + cnRatio_mean + PresentTreeCover_mean+CanopyHeight_mean, maxdepth = 3, mtry = 4, minsplit = 300, data = assogrids)


```

```{R}

ggparty(assotree)+
  geom_edge()+
  geom_edge_label()+
  geom_node_splitvar()+
  geom_node_plot(gglist = list(
                               geom_smooth(aes(x = assonegresidual,
                                               y = nppresidual),
                                           method = 'loess',color = 'blue', span = 1),
                               geom_point(aes(x = assonegresidual, y = nppresidual), alpha = 0.1),
                               theme_classic()
 
                 )
  )

```

##############################\


```{r}


assogrids <- assogrids %>%
  mutate(plotcount = case_when(nplot>=180~180,
                               nplot<180 ~ nplot))

subdf <- assogrids %>%
  dplyr::select(c(
    CHELSA_Annual_Mean_Temperature_mean,
    CHELSA_Annual_Precipitation_mean,
    CHELSA_Temperature_Annual_Range_mean,
    regionalrichness,
    height_mean,
    meandensity,
    plotcount,
    assosimple
  ))
```


```{r}

rmfls<-lm(scale(assosimple)~scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(regionalrichness)+scale(height_mean)+scale(meandensity) + scale(plotcount),data = subdf) # Linear model is set.
varls<-lm(scale(CHELSA_Annual_Mean_Temperature_mean)~scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(regionalrichness)+scale(height_mean)+scale(meandensity) + scale(plotcount),data = subdf)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)




```

```{r}

rmfls<-lm(scale(assosimple)~ scale(CHELSA_Annual_Mean_Temperature_std)+scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Annual_Precipitation_std)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(CHELSA_Temperature_Annual_Range_std)+scale(regionalrichness)+scale(height_mean)+scale(height_std)+scale(meandensity)+scale(stddensity)+scale(plotcount),data = assogrids) # Linear model is set.
varls<-lm(scale(CHELSA_Annual_Mean_Temperature_mean)~scale(CHELSA_Annual_Mean_Temperature_std)+scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Annual_Precipitation_std)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(CHELSA_Temperature_Annual_Range_std)+scale(regionalrichness)+scale(height_mean)+scale(height_std)+scale(meandensity)+scale(stddensity) + scale(plotcount),data = assogrids)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)




```


```{r}



rmfls<-lm(scale(assosimple)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(regionalrichness)+scale(height_mean)+scale(meandensity)+ scale(plotcount),data = subdf) # Linear model is set.
varls<-lm(scale(CHELSA_Annual_Precipitation_mean)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(regionalrichness)+scale(height_mean)+scale(meandensity)+ scale(plotcount),data = subdf)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)




```

```{r}



rmfls<-lm(scale(assosimple)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(regionalrichness)+scale(height_mean)+scale(meandensity)+scale(CHELSA_Annual_Mean_Temperature_std)+scale(CHELSA_Annual_Precipitation_std)+scale(CHELSA_Temperature_Annual_Range_std)+scale(height_std) + scale(stddensity)+ scale(plotcount),data = assogrids) # Linear model is set.
varls<-lm(scale(CHELSA_Annual_Precipitation_mean)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(regionalrichness)+scale(height_mean)+scale(meandensity)+scale(CHELSA_Annual_Mean_Temperature_std)+scale(CHELSA_Annual_Precipitation_std)+scale(CHELSA_Temperature_Annual_Range_std)+scale(height_std) + scale(stddensity)+ scale(plotcount),data = assogrids)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)




```



```{r}
rmfls<-lm(scale(assosimple)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(regionalrichness)+scale(height_mean)+scale(meandensity)+ scale(plotcount),data = subdf) # Linear model is set.
varls<-lm(scale(CHELSA_Temperature_Annual_Range_mean)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(regionalrichness)+scale(height_mean)+scale(meandensity)+ scale(plotcount),data = subdf)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)


```

```{r}
rmfls<-lm(scale(assosimple)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(regionalrichness)+scale(height_mean)+scale(meandensity)+scale(CHELSA_Annual_Mean_Temperature_std)+scale(CHELSA_Annual_Precipitation_std)+scale(CHELSA_Temperature_Annual_Range_std)+scale(height_std) + scale(stddensity)+ scale(plotcount),data = assogrids) # Linear model is set.
varls<-lm(scale(CHELSA_Temperature_Annual_Range_mean)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(regionalrichness)+scale(height_mean)+scale(meandensity)+scale(CHELSA_Annual_Mean_Temperature_std)+scale(CHELSA_Annual_Precipitation_std)+scale(CHELSA_Temperature_Annual_Range_std)+scale(height_std) + scale(stddensity)+ scale(plotcount),data = assogrids)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)


```




```{r}
rmfls<-lm(scale(assosimple)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(height_mean)+scale(meandensity)+ scale(nplot),data = assogrids) # Linear model is set.
varls<-lm(scale(regionalrichness)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(height_mean)+scale(meandensity)+ scale(nplot),data = assogrids)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)


```

```{r}
rmfls<-lm(scale(assosimple)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(height_mean)+scale(meandensity)+scale(CHELSA_Annual_Mean_Temperature_std)+scale(CHELSA_Annual_Precipitation_std)+scale(CHELSA_Temperature_Annual_Range_std)+scale(height_std) + scale(stddensity)+ scale(plotcount),data = assogrids) # Linear model is set.
varls<-lm(scale(regionalrichness)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(height_mean)+scale(meandensity)+scale(CHELSA_Annual_Mean_Temperature_std)+scale(CHELSA_Annual_Precipitation_std)+scale(CHELSA_Temperature_Annual_Range_std)+scale(height_std) + scale(stddensity)+ scale(plotcount),data = assogrids)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)


```



```{r}
rmfls<-lm(scale(assosimple)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(regionalrichness)+scale(meandensity)+ scale(plotcount),data = subdf) # Linear model is set.
varls<-lm(scale(height_mean)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(regionalrichness)+scale(meandensity)+ scale(plotcount),data = subdf)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)


```
```{r}
rmfls<-lm(scale(assosimple)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(regionalrichness)+scale(meandensity)+scale(CHELSA_Annual_Mean_Temperature_std)+scale(CHELSA_Annual_Precipitation_std)+scale(CHELSA_Temperature_Annual_Range_std)+scale(height_std) + scale(stddensity)+ scale(plotcount),data = assogrids) # Linear model is set.
varls<-lm(scale(height_mean)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(regionalrichness)+scale(meandensity)+scale(CHELSA_Annual_Mean_Temperature_std)+scale(CHELSA_Annual_Precipitation_std)+scale(CHELSA_Temperature_Annual_Range_std)+scale(height_std) + scale(stddensity)+ scale(plotcount),data = assogrids)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)


```


```{r}
rmfls<-lm(scale(assosimple)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(regionalrichness)+scale(height_mean)+ scale(plotcount),data = subdf) # Linear model is set.
varls<-lm(scale(meandensity)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(regionalrichness)+scale(height_mean)+ scale(plotcount),data = subdf)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)


```

```{r}
rmfls<-lm(scale(assosimple)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(regionalrichness)+scale(height_mean)+scale(CHELSA_Annual_Mean_Temperature_std)+scale(CHELSA_Annual_Precipitation_std)+scale(CHELSA_Temperature_Annual_Range_std)+scale(height_std) + scale(stddensity)+ scale(plotcount),data = assogrids) # Linear model is set.
varls<-lm(scale(meandensity)~scale(CHELSA_Annual_Mean_Temperature_mean)+scale(CHELSA_Annual_Precipitation_mean)+scale(CHELSA_Temperature_Annual_Range_mean)+scale(regionalrichness)+scale(height_mean)+scale(CHELSA_Annual_Mean_Temperature_std)+scale(CHELSA_Annual_Precipitation_std)+scale(CHELSA_Temperature_Annual_Range_std)+scale(height_std) + scale(stddensity)+ scale(plotcount),data = assogrids)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)


```


```{r}

items <- names(subdf)[1:6]

items

```



```{r}
coef <- c(-0.263, 0.101, -0.07, -0.364, -0.218, 0.088)

stdrr <- c(0.028, 0.03, 0.026, 0.029, 0.036, 0.028)

```


```{r}

olsdf <- cbind(coef, stdrr)
olsdf <- as.data.frame(olsdf)

olsdf <- cbind(olsdf, items)

```


```{r}

olsdf$items <- factor(olsdf$items, levels = c('meandensity', 'height_mean', 'regionalrichness', 'CHELSA_Temperature_Annual_Range_mean', 'CHELSA_Annual_Precipitation_mean', 'CHELSA_Annual_Mean_Temperature_mean'))

olsdf %>%
  ggplot(., aes(x = items, y = coef, color = coef/abs(coef)))+
  geom_point(stat = 'identity', size = 6.18)+
  geom_errorbar(aes(ymin = coef - 2*stdrr, ymax = coef + 2*stdrr), width = 0, size = 1, color = 'black')+
  scale_color_gradient(low = '#2166ac', high = '#b2182b')+
  coord_flip()+
  theme(legend.position = 'none', axis.title = element_blank(), axis.text = element_text(size = 20), panel.background = element_rect(fill = '#ffffff', color = 'grey50'))+
  geom_abline(slope = 0, intercept = 0, linetype = 'dashed', size = 1)
  


```

```{r}
coef <- c(-0.305,-0.01,-0.164, -0.38, -0.136, -0.094)

stdrr <- c(0.034, 0.042, 0.031, 0.03, 0.043, 0.057)
```

```{r}

olsdf <- cbind(coef, stdrr)
olsdf <- as.data.frame(olsdf)

olsdf <- cbind(olsdf, items)

```


```{r}

olsdf$items <- factor(olsdf$items, levels = c('meandensity', 'height_mean', 'regionalrichness', 'CHELSA_Temperature_Annual_Range_mean', 'CHELSA_Annual_Precipitation_mean', 'CHELSA_Annual_Mean_Temperature_mean'))

olsdf %>%
  ggplot(., aes(x = items, y = coef, color = coef/abs(coef)))+
  geom_point(stat = 'identity', size = 6.18)+
  geom_errorbar(aes(ymin = coef - 2*stdrr, ymax = coef + 2*stdrr), width = 0, size = 1, color = 'black')+
  scale_color_gradient(low = '#2166ac', high = '#b2182b')+
  coord_flip()+
  theme(legend.position = 'none', axis.title = element_blank(), axis.text = element_text(size = 20), panel.background = element_rect(fill = '#ffffff', color = 'grey50'))+
  geom_abline(slope = 0, intercept = 0, linetype = 'dashed', size = 1)
  


```
