---
title: "Untitled"
output: html_document
date: "2023-08-25"
---




```{R}

assogrids <- read.csv('~/Desktop/grid_level_association_50km_sig_180s_20240404_nocover.csv')

names(assogrids)


```



```{R}

library(readr)

library(ggplot2)

library(dplyr)

library(EnvStats)

library(outliers)

library(data.table)

library(h2o)

library(raster)

library(tictoc)

library(foreach)

library(doParallel)

library(zoo)

library(nlme)

library(HH)


```




```{R}

#test <- rosnerTest(assogrids[,'assosimple'], k = 100)$all.stats

#test <- test[test$Outlier == 'TRUE',]

#assogrids <- assogrids[-test$Obs.Num,]


"test <- rosnerTest(assogrids[,'assoneg'], k = 100)$all.stats

test <- test[test$Outlier == 'TRUE',]

assogrids <- assogrids[-test$Obs.Num,]
"

```
```{R}

library(mgcv)

ml <- gam(assosimple ~ regionalrichness, data = assogrids)
summary(ml)

assogrids$gamresi <- ml$residuals

```




```{R}


bandnames <- c(
  'CHELSA_Annual_Mean_Temperature_mean',
  'CHELSA_Annual_Mean_Temperature_std',
  'CHELSA_Annual_Precipitation_mean',
  'CHELSA_Annual_Precipitation_std',
  'CHELSA_Mean_Temperature_of_Coldest_Quarter_mean',
  'CHELSA_Mean_Temperature_of_Coldest_Quarter_std',
  'CHELSA_Temperature_Annual_Range_mean',
  'CHELSA_Temperature_Annual_Range_std',
  'CHELSA_Precipitation_of_Driest_Quarter_mean',
  'CHELSA_Precipitation_of_Driest_Quarter_std'
  #'CHELSA_Isothermality_mean',
  #'CHELSA_Isothermality_std',
  #'PET_mean',
  #'PET_std'
)
```


```{r}
climdf <- assogrids %>%
  dplyr::select(bandnames)

climpca <- prcomp(climdf, center = T, scale.=T)

summary(climpca)

climmatrix <- climpca$x

climmatrix <- as.data.frame(climmatrix)

names(climmatrix) <- c('climpc1', 'climpc2', 'climpc3', 'climpc4', 'climpc5',
                       'climpc6','climpc7', 'climpc8', 'climpc9', 'climpc10'
                       )


subclim <- climmatrix[,1:5]

```


```{R}
bandnames <- c(
  'SG_Sand_Content_0_100cm_mean',
  'SG_Sand_Content_0_100cm_std',
  'SG_Soil_pH_H2O_0_100cm_mean',
  'SG_Soil_pH_H2O_0_100cm_std',
  'cnRatio_mean',
  'cnRatio_std',
  #'SG_Clay_Content_0_100cm_mean',
  #'SG_Clay_Content_0_100cm_std',
  #'SG_Silt_Content_0_100cm_mean',
  #'SG_Silt_Content_0_100cm_std',
  'SG_Absolute_depth_to_bedrock_mean',
  'SG_Absolute_depth_to_bedrock_std'
)


```

```{r}
soildf <- assogrids %>%
  dplyr::select(bandnames)

soilpca <- prcomp(soildf, center = T, scale.=T)

summary(soilpca)

soilmatrix <- soilpca$x

soilmatrix <- as.data.frame(soilmatrix)

names(soilmatrix) <- c('soilpc1', 'soilpc2', 'soilpc3', 'soilpc4',
                       'soilpc5', 'soilpc6', 'soilpc7', 'soilpc8'
                       #'soilpc9', 'soilpc10', 'soilpc11', 'soilpc12'
                       )

subsoil <- soilmatrix[,1:5]

```


```{R}
bandnames <- c(
  'EarthEnvTopoMed_Elevation_mean',
  'EarthEnvTopoMed_Elevation_std',
  'EarthEnvTopoMed_Slope_mean',
  'EarthEnvTopoMed_Slope_std',
  'EarthEnvTopoMed_Roughness_mean',
  'EarthEnvTopoMed_Roughness_std'
  #'EarthEnvTopoMed_AspectSine_mean',
  #'EarthEnvTopoMed_AspectCosine_mean',
  #'EarthEnvTopoMed_Eastness_mean',
  #'EarthEnvTopoMed_Eastness_slope',
  #'EarthEnvTopoMed_Northness_mean',
  #'EarthEnvTopoMed_Northness_std'
)


```

```{r}
topodf <- assogrids %>%
  dplyr::select(bandnames)

topopca <- prcomp(topodf, center = T, scale.=T)

summary(topopca)

topomatrix <- topopca$x

topomatrix <- as.data.frame(topomatrix)

names(topomatrix) <- c('topopc1', 'topopc2', 'topopc3', 'topopc4', 'topopc5', 'topopc6')

subtopo <- topomatrix[,1:5]

```






```{R}
bandnames <- c(
  #'PresentTreeCover_mean',
  #'PresentTreeCover_std',
  'NDVI_mean',
  'NDVI_std',
  'meandensity',
  'stddensity',
  'regionalrichness'
)


```

```{r}
vegdf <- assogrids %>%
  dplyr::select(bandnames)

vegpca <- prcomp(vegdf, center = T, scale.=T)

summary(vegpca)

vegmatrix <- vegpca$x

vegmatrix <- as.data.frame(vegmatrix)

names(vegmatrix) <- c('vegpc1', 'vegpc2', 'vegpc3',
                      'vegpc4',
                      'vegpc5'
                      )

subveg <- vegmatrix[,1:5]

```
```{R}

vartomodel <- 'associatoinsimplespear'

```



```{R}

regressionmatrix <- bind_cols(subclim, subsoil, subveg, subtopo, assogrids$associatoinsimplespear)

colnames(regressionmatrix)[21] <- 'associatoinsimplespear'


#names(regressionmatrix) <- c('climpc1', 'climpc2', 'climpc3', 'climpc4', 'climpc5', 'climpc6',
 #                            'soilpc1', 'soilpc2', 'soilpc3', 'climpc4', 'climpc5', 'climpc6',
#                             'topopc1', 'topopc2', 'topopc3', 'topopc4', 'topopc5', 'topopc6',
#                             'vegpc1', 'vegpc2', 'vegpc3','asso')


```



```{R}

cor.matrix <- cor(regressionmatrix[,c(1:ncol(regressionmatrix)-1)], use = 'complete.obs', method = 'pearson')
cor.dist <- abs(as.dist(cor.matrix))
cor.cluster <- hclust(1-cor.dist)

plot(cor.cluster)


```
```{R}

library(HH)

ds <- regressionmatrix[,c(1:(ncol(regressionmatrix)-1))]
ds <- as.data.frame(ds)
vif(ds)


```

```{R}

localH2O <- h2o.init(nthreads = 8, max_mem_size = '10g', ignore_config = TRUE)

regmatrixh2o <- as.h2o(regressionmatrix, destination_frame = 'regMatrixH2O')

rf.params <- list(ntrees = 400,
                  mtries = c(1:15),
                  min_rows = c(1:20))


search.criteria <- list(strategy = 'RandomDiscrete', max_models = 150, seed = 0, max_runtime_secs = 600)



```


```{R}
rf.grid<-h2o.grid('randomForest',
                  y = vartomodel,
                  grid_id = 'rf.grid',
                  training_frame = regmatrixh2o,
                  seed = 0,
                  hyper_params = rf.params,
                  sample_rate = 0.632,
                  nfolds = 10,
                  fold_assignment = 'AUTO',
                  keep_cross_validation_predictions = TRUE, # Important!
                  keep_cross_validation_fold_assignment = TRUE, # Important!
                  search_criteria = search.criteria)

```



retrieve grid searched model performance sort by RMSE/R2


```{R}
rf.grid.perf<-h2o.getGrid(grid_id = 'rf.grid',
                          sort_by = 'R2', # This is also coefficient of determinaion values
                          decreasing = TRUE)
```





```{R}
print(rf.grid.perf@summary_table)
```


```{R}

for(i in 1:10){

rfmodel <- h2o.getModel(rf.grid.perf@model_ids[[i]])

p1<-h2o.varimp_plot(rfmodel)

print(p1)

varip<-h2o.varimp(rfmodel)

varip

library(readr)

write_csv(varip, paste0('~/Desktop/bestmodel_assospear_notopo_all',i,'_pca_sig_varip_20240404.csv'))


print(h2o.r2(rfmodel))
#h2o.rmse(rfmodel)

}

```


```{R}
h2o.shutdown(prompt = FALSE)

```






